In [9]:
#Question 1

a=[]
for x in range(2000, 3200):
    if (x%7==0) and (x%5==0):
        a.append(str(x))
print (','.join(a))

2030,2065,2100,2135,2170,2205,2240,2275,2310,2345,2380,2415,2450,2485,2520,2555,2590,2625,2660,2695,2730,2765,2800,2835,2870,2905,2940,2975,3010,3045,3080,3115,3150,3185


In [1]:
#Question 2

n = int(input("Enter a number "))

factorial = 1

if n < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif n == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,n + 1):
       factorial = factorial*i
   print("The factorial of",n,"is",factorial)

Enter a number 3
The factorial of 3 is 6


In [17]:
#Question 3

number = int(input("Enter a number: "))

numberDict = {}
for i in range(1, number+1):
    numberDict[i] = i*i

print(numberDict)


Enter a number: 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [145]:
def missing_char(word, index):
    if len(word) > index:
        word = word[0 : index : ] + word[index + 1 : :]
        return word
    else:
        return "invalid index"

missing_char('kitten', 0) #→ 'ktten'
missing_char('kitten', 1) #→ 'itten'
missing_char('kitten', 3) #→ 'kittn'


'kiten'

In [4]:
# Question 4
def remove_char_from(word, c):
  result = filter(lambda x: x != c.lower() and x != c.upper(), word)
  return "".join(result)

# Testing Ouput
print(remove_char_from("kitten", "k"))  # itten
print(remove_char_from("kitten", "i"))  # ktten
print(remove_char_from("kitten", "t"))  # kiten
print(remove_char_from("kitten", "t"))  # kikten
print(remove_char_from("kitten", "e"))  # kittn
print(remove_char_from("kitten", "n"))  # kitte


itten
ktten
kien
kien
kittn
kitte


In [5]:
#Question 5

import numpy as np
x= np.arange(6).reshape(3, 2)
print("the Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

the Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [189]:
#Question 6

import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [6]:
#Question 7

import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)

Provide D: 6
[4]


In [9]:
import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)

Provide D: 100,500,88
[18, 41, 17]
